server:
  port: 8866
spring:
  application:
    name: classManager
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reboot
    username: root
    password: root123

  mail:
    default-encoding: UTF-8 #默认的邮件编码
    username: 264494336@qq.com
    password: yqmmenyzdqnfcbcg
    host: smtp.qq.com
    properties:
      mail:
        debug: true
        smtp:
          ssl:
            enable: true


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      id-type: assign_id
  mapper-locations: classpath:/mapper/*.xml

binace:
  api: none
  stream:
    fstream: wss://fstream.binance.com/ws/